# Generated by Django 3.2.5 on 2021-08-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMAA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_maa', models.CharField(choices=[('TS', 'Orage')], max_length=20)),
            ],
        ),
    ]
