# Generated by Django 3.2.5 on 2021-08-22 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configmaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmaa',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.station'),
            preserve_default=False,
        ),
    ]
