# Generated by Django 3.2.5 on 2021-08-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configmaa_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmaa',
            name='auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configmaa',
            name='pause',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='configmaa',
            name='profondeur',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='configmaa',
            name='scan',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='configmaa',
            name='seuil',
            field=models.FloatField(null=True),
        ),
    ]
