# Generated by Django 3.2.5 on 2021-08-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210822_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmaa',
            name='seuil',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configmaa',
            name='type_maa',
            field=models.CharField(choices=[('TS', 'Orage'), ('SQ', 'Grain')], max_length=20),
        ),
    ]
