# Generated by Django 3.2.5 on 2021-08-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210822_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
