# Generated by Django 3.2.5 on 2021-08-27 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_station_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvoiMAA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('numero', models.IntegerField()),
                ('message', models.TextField()),
                ('context_TAF', models.TextField(null=True)),
                ('context_CDPH', models.TextField(null=True)),
                ('context_CDPQ', models.TextField(null=True)),
                ('log', models.TextField(null=True)),
                ('message_mail', models.TextField(null=True)),
                ('message_pdf', models.FileField(null=True, upload_to='')),
                ('message_sms', models.TextField(null=True)),
                ('configmaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.configmaa')),
            ],
        ),
    ]
