# Generated by Django 3.2.5 on 2021-08-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_envoimaa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmaa',
            name='type_maa',
            field=models.CharField(choices=[('TS', 'Orage'), ('SQ', 'Grain'), ('DENSE_FG', 'Brouillard dense'), ('SN', 'SN'), ('FZDZ', 'FZDZ'), ('VENT_MOY', 'VENT_MOY'), ('VEHICLE_RIME', 'VEHICLE_RIME '), ('TMIN', 'TMIN '), ('HVY_GR', 'HVY_GR '), ('TOXCHEM', 'TOXCHEM '), ('TC', 'TC '), ('DU', 'DU '), ('TMAX', 'TMAX '), ('HVY_SN', 'HVY_SN '), ('FG', 'FG '), ('HVY_TS', 'HVY_TS '), ('FWOID', 'FWOID '), ('ICE_DEPOSIT', 'ICE_DEPOSIT '), ('RR1', 'RR1 '), ('RR3', 'RR3 '), ('RR6', 'RR6 '), ('RR12', 'RR12 '), ('RR24', 'RR24 '), ('HVY_FZDZ', 'HVY_FZDZ '), ('FWID', 'FWID '), ('FZRA', 'FZRA '), ('GR', 'GR '), ('VENT', 'VENT '), ('RIME', 'RIME '), ('VA', 'VA '), ('HVY_FZRA', 'HVY_FZRA '), ('SNRA', 'SNRA '), ('SA', 'SA '), ('HVY_SNRA', 'HVY_SNRA '), ('SEA', 'SEA '), ('FZFG', 'FZFG '), ('BLSN', 'BLSN '), ('TSUNAMI', 'TSUNAMI '), ('HVY_SWELL', 'HVY_SWELL')], max_length=20),
        ),
    ]
