# Generated by Django 3.2.5 on 2021-08-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='envoimaa',
            name='fcst',
            field=models.BooleanField(default=True),
        ),
    ]
