# Generated by Django 3.2.5 on 2021-08-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_envoimaa_fcst'),
    ]

    operations = [
        migrations.AddField(
            model_name='envoimaa',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('pending', 'En cours de traitement'), ('send', 'Envoyé')], default='new', editable=False, max_length=10),
        ),
    ]
