# Generated by Django 3.2.5 on 2021-09-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_envoimaa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='stations',
            field=models.ManyToManyField(to='core.Station'),
        ),
        migrations.AlterField(
            model_name='envoimaa',
            name='status',
            field=models.CharField(choices=[('to_send', 'Nouveau'), ('submit', 'Edité'), ('ok', 'Envoyé')], default='new', editable=False, max_length=10),
        ),
    ]
