# Generated by Django 3.2.5 on 2021-09-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_configmaa_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='stations',
        ),
    ]
