# Generated by Django 3.2.5 on 2021-09-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='inseepp',
            field=models.CharField(default=1234567, max_length=7, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configmaa',
            name='type_maa',
            field=models.CharField(choices=[('BLSN', 'BLSN '), ('DENSE_FG', 'Brouillard dense'), ('DU', 'DU '), ('FG', 'FG '), ('FWID', 'FWID '), ('FWOID', 'FWOID '), ('FZDZ', 'FZDZ'), ('FZFG', 'FZFG '), ('FZRA', 'FZRA '), ('GR', 'GR '), ('HVY_FZDZ', 'HVY_FZDZ '), ('HVY_FZRA', 'HVY_FZRA '), ('HVY_GR', 'HVY_GR '), ('HVY_SN', 'HVY_SN '), ('HVY_SNRA', 'HVY_SNRA '), ('HVY_SWELL', 'HVY_SWELL'), ('HVY_TS', 'HVY_TS '), ('ICE_DEPOSIT', 'ICE_DEPOSIT '), ('RIME', 'RIME '), ('RR1', 'RR1 '), ('RR12', 'RR12 '), ('RR24', 'RR24 '), ('RR3', 'RR3 '), ('RR6', 'RR6 '), ('SA', 'SA '), ('SEA', 'SEA '), ('SN', 'SN'), ('SNRA', 'SNRA '), ('SQ', 'Grain'), ('TC', 'TC '), ('TMAX', 'TMAX '), ('TMIN', 'TMIN '), ('TOXCHEM', 'TOXCHEM '), ('TS', 'Orage'), ('TSUNAMI', 'TSUNAMI '), ('VA', 'VA '), ('VEHICLE_RIME', 'VEHICLE_RIME '), ('VENT', 'VENT '), ('VENT_MOY', 'VENT_MOY')], max_length=20),
        ),
    ]
