# Generated by Django 3.2.5 on 2021-09-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210919_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.DateTimeField(auto_created=True)),
                ('type', models.CharField(choices=[('error', 'Erreur'), ('warning', 'Avertissement'), ('info', 'Information')], max_length=10)),
                ('machine', models.CharField(max_length=20)),
                ('code', models.IntegerField(null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='station',
            name='inseepp',
            field=models.CharField(max_length=7, verbose_name='INSEEpp'),
        ),
    ]
