# Generated by Django 3.2.5 on 2021-09-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_logs_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='outremer',
            field=models.BooleanField(default=False),
        ),
    ]
